### ISSUE TITLE
How to use with 2FA

### ISSUE THREAD

**Issue by boiUneedAwash** [moismailzai/ansible-role-protonmail-bridge-headless#1]
Would I have to remove 2FA to use this, looks really good and could help people use their proton accounts with next cloud.

Thanks for the work

**Comment by moismailzai** [comment]
Glad it's useful! When enabled, 2FA will generate a code during the login attempt which the user will have to manually retrieve and input into the bridge application. This means the role would require user action. I could add it as a non-default variable... let me play around with it this weekend :)

**Comment by moismailzai** [comment]
hi @boiUneedAwash , this has been implemented. see the updated readme for additional information.
